### PR TITLE
Update README.md

### LINKED ISSUE #2: Create Spanish Documentation
- Creation curriculum documentation in spanish

### PR DESCRIPTION
**Pull request by d4n13lbc**
- Update curriculum documentation in spanish

### CODE REVIEW

**Comment by d4n13lbc** [comment]
Could I get an approval for this? @jmaquin0

**Review by jmaquin0 — COMMENTED** [review]
LGTM. 
I have a digital copy of pycharm official books without DRM, i'll send copies to @willy23martin and @d4n13lbc and i'll add it to references for the course

**Review by jmaquin0 — COMMENTED** [review]
LGTM.
I have a digital copy of pycharm official books without DRM, i'll send copies to @willy23martin and @d4n13lbc and i'll add it to references for the course

**Review by jmaquin0 — APPROVED** [review]

**Comment by d4n13lbc** [comment]
Awesome thanks , please share @jmaquin0

**Pull request merged**
